name: Forg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Android SDK
      run: echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH
    - name: Build Jar
      run: ./gradlew deploy
    - name: Grant execute permissions
      run: |
        chmod +x gradlew
        chmod +x alpha-bleed
        chmod +x alpha-bleeding-linux.exe
    - name: Build with Gradle
      run: ./gradlew alphableed buildDex

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
